[build]
  command = "npx @11ty/eleventy"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  
[dev]
  command = "npx @11ty/eleventy --serve"
  port = 8888
  targetPort = 8080
  publish = "public"
  framework = "#custom"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
